#!/usr/bin/env bash

# cron it with
#  5 4 * * 0 /usr/local/bin/routine >> /var/log/sysupgrade.log 2>&1

echo "###" && date && echo "###"

if [ $(which apt 2>/dev/null ) ]; then
	apt update									&& \
	apt list --upgradable						&& \
	apt full-upgrade -y							&& \
	apt update && apt upgrade -y				&& \
	apt update && apt full-upgrade -y			&& \
	apt clean && apt autoclean

elif [ $(which xbps-install 2>/dev/null ) ]; then
	xbps-install -Suvy && xbps-remove -fOovy	&& \
	xbps-install -Suvy && xbps-remove -fOovy	&& \
	xbps-install -Suvy && xbps-remove -fOovy	&& \
	vkpurge list
fi